### ISSUE TITLE
Slider is broken

### ISSUE THREAD

**Issue by philippotto** [xeodou/react-range-slider#15]
In Chrome 49.0.2623.75 m (64-bit, Windows) `"ontouchstart" in window` evaluates to true, which is why isTouchDevice() returns true, even though I'm at a desktop pc.

That's why I get the following error at the following line when trying to drag a cursor.

`Uncaught TypeError: Cannot read property 'length' of undefined`

`e = this.isTouchDevice() ? e.changedTouches[e.changedTouches.length - 1] : e;`

https://github.com/xeodou/react-range-slider/blob/1bb012f17b2460571e2e02d51bbd7b86256f517b/index.js#L304

**Comment by isnifer** [comment]
Haha, nice! There is `ontouchstart` in major version only on OS X too.
But, Chrome Canary doesn't have it:
![image](https://cloud.githubusercontent.com/assets/1788245/13546589/8a24c1b6-e2c3-11e5-96c8-1278825c55c6.png)

**Comment by isnifer** [comment]
@philippotto I tried to run demo page on Stable Chrome. Look:
![image](https://cloud.githubusercontent.com/assets/1788245/13546614/feb0160c-e2c3-11e5-8a1e-a439fa40e8b4.png)

**Comment by isnifer** [comment]
@philippotto Do you reproduce this bug only when change view from mobile to desktop?

**Comment by philippotto** [comment]
After some digging, I'm pretty sure this is a chrome bug. At first, I thought they changed the implementation deliberately and `"ontouchstart" in window` is not working as an indicator for touch, anymore, but after having read the following threads, it just seems to be a bug on certain systems (e.g. when the touchpad "acts like a touchpad" (pinch-zoom etc.)).

https://bugs.chromium.org/p/chromium/issues/detail?id=467934
https://bugs.chromium.org/p/chromium/issues/detail?id=557565

> @philippotto Do you reproduce this bug only when change view from mobile to desktop?

I'm not sure, whether I understand your question, but this bug already occurs when visiting the demo page in my desktop browser without any mobile switches in the devtools.

At the moment, I think there are two possible solutions:
1. Wait for Chrome to fix this. This could take a while since the reports were already opened some months ago. However, I assume that this is a recent regression, since the slider worked just a few days ago on my machine.
2. Rewrite the code so that this bug is circumvented.

Usually, I would say 1) is the way to go, since this library shouldn't be responsible for this chrome quirk (which seems to only happen in some browsers). However, after having looked at the code, I think, the implementation isn't "best practice" anyway. To be specific, I doubt that the code works, when you have a touch device which also has a touchpad/mouse (e.g. a "convertible" or "hybrid" computer).

I will fork this repository and will have a look, if we can have an implementation which doesn't introduce ugly workarounds and still fixes the bug I'm experiencing.

**Comment by isnifer** [comment]
@philippotto so strange, I've got this bug only when switched from mobile view to desktop view.
I reproduce this bug like that - https://bugs.chromium.org/p/chromium/issues/detail?id=467934#c14

**Comment by philippotto** [comment]
@isnifer Weird, for me it reproduces without the desktop->mobile->desktop switch. I can just open a new tab and open the demo to reproduce it.

I just filed a PR which should fix this issue :)

**Comment by isnifer** [comment]
@philippotto Nice, I think about something similar for solution to the problem.
I will test your solution on my own fork. I published it on npm because that component was updated 4 months ago.

**Comment by xeodou** [comment]
Hi guys
Thanks for reporting this issue, I will check the PR and see if i can have a release today.

**Comment by xeodou** [comment]
Hi guys, i just publish version 0.2.1 . Thanks all.

**Comment by philippotto** [comment]
Awesome, thank you!
