### ISSUE TITLE
Problem trying to use this widget throught npm

### ISSUE THREAD

**Issue by dgarciap** [xeodou/react-range-slider#2]
Hi!
First of all thanks you for sharing this slider ;)

I've got a problem while trying to use it. When I execute: 
´´´
npm install react-range-slider
´´´
CSS file is not include in the library, just a scss file inside examples folder. So the slider is just a white space.

I cannot see anything.

Could you include a compiled css and apply it over your slider when using it as a react component automatically?

Meanwhile, I will compile it myself and place it in my css folder.

Thank you in adavance!

**Comment by xeodou** [comment]
Hi @dgarciap 

I have put a compiled css file in gh-page branch which is here https://github.com/xeodou/react-range-slider/blob/gh-pages/style.css

And this component does not contain any css. You need define by your self.  You can see demo here 
http://xeodou.github.io/react-range-slider/

And i am working on improve the component and clean the code.

Open an issue if you have question.
