### ISSUE TITLE
onAfterChange is called twice

### ISSUE THREAD

**Issue by luxflux** [xeodou/react-range-slider#9]
The `onAfterChange` is called twice, is this a bug or did I miss something?

Following code:

``` coffeescript
React = require 'react'

Slider = require 'react-range-slider'

RangeFilter = React.createClass
  changeCallback: (event, value) ->
    console.log 'got called'

  render: ->
    <div>
      <h2>{@props.title}</h2>
      <Slider min={100} max={1000} cursor value={[200, 800]} onAfterChange={@changeCallback} />
    </div>

module.exports = RangeFilter
```

After dragging the slider, I've got two times `got called` in the console.

**Comment by xeodou** [comment]
@luxflux let me check. Your demo seems good.

**Comment by luxflux** [comment]
Cool! Looking forward to your feedback :smile:

**Comment by xeodou** [comment]
@luxflux I just fixed the issue. Please try 0.2.0 version.

**Comment by luxflux** [comment]
Yay, fixed! Thank you.
